database:
  host: "127.0.0.1"
  port: 5433
  username: "neil"
  # password: "password"
  database_name: "pine_tails_dev"
gmail_service:
  token_api: "https://oauth2.googleapis.com/token"
  email_api: "https://gmail.googleapis.com/gmail/v1/users/me/messages/send"
